version: '3'

services:
  node_mysql:
    image: mysql
    container_name: node_mysql
    restart: always
    ports:                          # 映射端口
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:                        # 挂载数据卷
      - /root/mysql:/var/lib/mysql  # 为了数据持久化
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:                       # 加入指定网络
      - app-network 

  nodejs:
    build:                          # 这里指的是我们刚刚撸的 Dockerfile 文件
      context: .                    
      dockerfile: Dockerfile
    image: nodejs                   # 镜像名称
    container_name: nodejs          # 容器名称
    restart: always                 # 重启方式
    depends_on:                     # 启动顺序
      - node_mysql
    links:                          # 容器连接
      - node_mysql:node_mysql
    networks:                       # 加入指定网络
      - app-network
    ports:
        - '8099:8099'
networks:  # 实现通信
  app-network:
    driver: bridge
